logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Tablet mini player' 'Hide autoplay button' 'Hide captions button' 'Hide video action buttons' 'Hide cast button' 'Spoof app version' 'Enable tablet layout' 'Hide info cards' 'Hide endscreen cards' 'Disable fullscreen ambient mode' 'Hide seekbar' 'Hide timestamp' 'Disable suggested video end screen' 'Wide searchbar' 'Seekbar tapping' 'Disable precise seeking gesture' 'Always autorepeat' 'Client spoof' 'Spoof device dimensions' 'Disable zoom haptics'"
included-patches = "'Add splash animation' 'MaterialYou'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Music]
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "both"

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
